version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
